# see controllers: http://control.ros.org/ros2_controllers/doc/controllers_index.html
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

position_trajectory_controller:
  ros__parameters:
    joints:
      - lbr_joint_0
      - lbr_joint_1
      - lbr_joint_2
      - lbr_joint_3
      - lbr_joint_4
      - lbr_joint_5
      - lbr_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    