# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - position_trajectory_controller

  position_trajectory_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - lbr_joint_0
      - lbr_joint_1
      - lbr_joint_2
      - lbr_joint_3
      - lbr_joint_4
      - lbr_joint_5
      - lbr_joint_6
